In [ ]:
# Google Cloud Project
PROJECT_ID = "adcz-adoki-poc"
LOCATION_ID = "europe-west1"

print(f"Project '{PROJECT_ID}' on a Location '{LOCATION_ID}'")

## Google BigQuery

In [ ]:
# Prepare variables
LOCATION_ID = "europe-west1"
PROJECT_ID = "adcz-adoki-poc"

dataset_id = "subs_property_dataset" # "demo_real_estate"
table_id = "property_type"

bq_table = f"{PROJECT_ID}.{dataset_id}.{table_id}"


# Get data from BQ table
df_bq_table = (
    spark.read.format("bigquery")
        .option("table", bq_table)
        .option("location", LOCATION_ID)
        .load()
)

df_property_type = df_bq_table

df_bq_table.show(10)

## Google Cloud Storage

In [ ]:
# Prepare vaiables
file_location = "gs://adastra-demo-real-estate/Properties list/dbx_property.csv"

# Get data from GCS
df_gcs = spark.read.csv(file_location, header=True, inferSchema=True)

df_property = df_gcs

df_gcs.show(5)

## External DB

In [ ]:
# Secret Manager
%pip install google-cloud-secret-manager
%pip install psycopg2-binary

In [22]:
from google.cloud import secretmanager

# Secret Manager setup remains the same
secret_id = "external-dataset-eff"
secret_client = secretmanager.SecretManagerServiceClient()
secret_name = f"projects/{PROJECT_ID}/secrets/{secret_id}/versions/latest"
secret_response = secret_client.access_secret_version(request={"name": secret_name})
pg_password = secret_response.payload.data.decode("UTF-8")

Project 'adcz-adoki-poc' on a Location 'europe-west1'

In [26]:
import pandas as pd
from sqlalchemy import create_engine

# Define connection parameters
pg_user = "server_role"
pg_host = "35.187.3.132"
pg_port = "5432"
pg_database = "Live"
pg_schema = "l2_stats"
pg_table = "cron"

connection_string = f"postgresql+psycopg2://{pg_user}:{pg_password}@{pg_host}:{pg_port}/{pg_database}"

try:
    engine = create_engine(connection_string)
    df_pg = pd.read_sql_table(pg_table, con=engine, schema=pg_schema)

    display(df_pg)

except Exception as e:
    print(f"An error occurred: {e}")

finally:
    if 'engine' in locals():
        engine.dispose()

,runid,jobid,date,start_time,end_time,run_time,procedure,return_message,ins_dt,upd_dt,del_flag
0,361,68,2024-02-23,10:12:00.018840+00:00,10:12:01.626024+00:00,0 days 00:00:01.607184,L1_POST_FACT_IG001(),CALL,2024-05-14,2024-05-14,False
1,322,51,2024-02-23,03:10:00.020441+00:00,03:10:00.046742+00:00,0 days 00:00:00.026301,L1_IMG_IG001,ERROR: syntax error at end of input,2024-05-14,2024-05-14,False
2,323,52,2024-02-23,03:10:00.035192+00:00,03:10:00.048261+00:00,0 days 00:00:00.013069,L1_IMG_FB001,ERROR: syntax error at end of input,2024-05-14,2024-05-14,False
3,324,50,2024-02-23,03:10:00.039347+00:00,03:10:00.268513+00:00,0 days 00:00:00.229166,L1_CLIENT_OTH01_CZ(),CALL,2024-05-14,2024-05-14,False
4,341,58,2024-02-23,03:12:00.073415+00:00,03:12:00.101174+00:00,0 days 00:00:00.027759,L1_AD_FACT_FB001,ERROR: syntax error at end of input,2024-05-14,2024-05-14,False
...,...,...,...,...,...,...,...,...,...,...,...
7991,8325,149,2024-05-15,04:35:07.257225+00:00,04:35:32.596359+00:00,0 days 00:00:25.339134,L2_GOOGLE_COST_IMPORT(),CALL,2024-05-15,2024-05-15,False
7992,8324,133,2024-05-15,04:35:00.452668+00:00,04:35:42.402182+00:00,0 days 00:00:41.949514,L2_REPORT_IG_INSIGHTS_PAGE_STATS(),CALL,2024-05-15,2024-05-15,False
7993,8321,132,2024-05-15,04:35:00.014966+00:00,04:35:42.550955+00:00,0 days 00:00:42.535989,L2_REPORT_FB_INSIGHTS_PAGE_STATS(),CALL,2024-05-15,2024-05-15,False
7994,8322,71,2024-05-15,04:35:00.022244+00:00,04:37:06.656881+00:00,0 days 00:02:06.634637,L2_REPORT_FB_ADS_DATA(),CALL,2024-05-15,2024-05-15,False
7995,8327,178,2024-05-15,04:45:00.005610+00:00,04:45:06.424220+00:00,0 days 00:00:06.418610,L2_STATS_PLATFORM_DATA(),CALL,2024-05-15,2024-05-15,False